### ISSUE TITLE
Regarding setting up of x-heep flow

### ISSUE THREAD

**Issue by shankar59** [davidmallasen/F-HEEP#3]
Hi @davidmallasen for this particular work, did you set up the x-heep flow using docker or the manual one ?

I'm facing some issues with both the flows so that's why wanted to check with you.

We're are interested in setting up the X-HEEP with a custom CNN accelerator that our group has developed and for that we intend to use F-HEEP as the starting point.

Thanks and Regards,
Shankar.

**Comment by davidmallasen** [comment]
Hello Shankar. I use the manual flow, but the docker one should also work. You need to set up the conda environment to interact with X-HEEP.

Best,
David

**Comment by shankar59** [comment]
And regarding the XIF interface integration. Is it taken care in the x-heep toolchain itself or should we manually add the interface rtl for our custom accelerator ?

Thanks and Regards,
Shankar.

**Comment by davidmallasen** [comment]
Your accelerator should support the XIF, and then you connect it to X-HEEP's XIF that is connected to the cv32e40px core.

**Comment by shankar59** [comment]
Thank You David.

Regards,
Shankar.
